### PR TITLE
Location Hash Options

### LINKED ISSUE #14: Query String Options
All options should be, additionally, stored in the querystring of the page so that the links could be shareable and back/forward buttons work.

### PR DESCRIPTION
**Pull request by kalisjoshua**
1. Persist the options object to the location hash.
  2. Parse the options object out of the location hash.
  3. Add reset button to get to default application state.
  4. Adjust styling of options tables to align within container.

closes #14

### CODE REVIEW

**Comment by kalisjoshua** [comment]
Ping.

**Comment by kalisjoshua** [comment]
Awesome!

**Comment by Thorinair** [comment]
Sorry that it took ages to accept this. Please check if everything works as expected. I had to do some fixes.

**Comment by kalisjoshua** [comment]
Just glad it was helpful. It's been a while since I created it so I don't remember how it should work so... It seems to be working from a quick look.

**Pull request merged**
