### PR TITLE
Updates to Dehydrator

### PR DESCRIPTION
**Pull request by doodlebunnyhops**
### Fix:
1. Processing Per Harvest - not total by season
2. Dehydrator Ignores the need of keeping half the produce for seeds, if Process & Replant is enabled
3. Check if equipment is used

### CODE REVIEW

**Comment by doodlebunnyhops** [comment]
Hey @Thorinair I'm actively working through this and was focusing on number 2: Adding dehydrator to account for Process & Replant if enabled.

I see where the forSeed section is taking place but I'm not sure if I'm missing something, the calculation seems slightly off to me. 
Wanted to touch base - see what I'm missing or if this needs massaging. 

I'm rather visual so as an example I used Red Cabbage and StarFruit
- Planted 2
- Pay for Seeds True
- Process & Replant True

The part I'm hung up on is paying for the initial seeds, but wouldn't there be a few more needed to purchase to maintain 2 replants each harvest?

mermaid-diagram-2024-05-24-220855

mermaid-diagram-2024-05-24-220621

**Comment by Thorinair** [comment]
The way how the Process & Replant works is that it accounts for the fact that you get 2 seeds per processing on average. This means that when you do plant 2 crops, you only pay for the initial seeds, and after that it keeps reusing the seeds that you process from 1 crop to plant 2, and you sell the one extra.

**Comment by doodlebunnyhops** [comment]
Ah thanks! That's what I was missing - carrying on 🥰

**Comment by doodlebunnyhops** [comment]
I do have another question for you, couple of ways to handle number of crops planted for dehydrator. Like replant it requires divisible by 2 crops - we could approach the same for dehydrator but that would obviate the excess calculations. Have thoughts preferences?

**Comment by Thorinair** [comment]
The way how I would approach is that if it has a number non-divisible by 5, it basically sells the rest normally (if that is enabled, the Dehydrator Excess: Sell Raw option), so in case when you have:
- 10 planted and reprocess and plant enabled, that is 5 available for dehydrator, so it gets used
- 9 planted and reprocess and plant enabled, only 4 are available and will be sold if dehydrator excess is enabled
- 8 is enabled and NOT reprocess and plant, 5 are used for dehydrator, rest sold
etc :D

**Comment by doodlebunnyhops** [comment]
More updates - think this should resolve the original asks. I did create some more functions, they helped me see where I was straying but also potentially could be reused in a few places.

**Comment by Thorinair** [comment]
Very nice! I can pull it to the dev to give it a test if you feel like it is ready!

**Comment by doodlebunnyhops** [comment]
I actually want to check 2 things - I  don't see that I've add atri buff to grapes and I need to also check I did till buff

**Comment by doodlebunnyhops** [comment]
:D ready!

**Comment by Thorinair** [comment]
Awesome! I will be pulling it tomorrow and integrating!

**Comment by Thorinair** [comment]
I am actually not sure if it is working correctly, having default settings, with spring active, and just activating dehydrator says that there is 1 item sold for Strawberries, but it should be 0 if there is just 1 planted

**Comment by doodlebunnyhops** [comment]
> I am actually not sure if it is working correctly, having default settings, with spring active, and just activating dehydrator says that there is 1 item sold for Strawberries, but it should be 0 if there is just 1 planted

default will accumulate all harvests to see how many can be sold

**Comment by Thorinair** [comment]
Oh, I understand, I think we can leave it like that, although I am not sure how to activate the processing per harvest

**Comment by doodlebunnyhops** [comment]
😅 yea now I understand your ask - I mistook for calculating using harvest total - ask was to show pee harvest how many dehydrated items, I can make a new pr

**Comment by doodlebunnyhops** [comment]
But even using equipment will accommodate unused produce to the last harvest 🤔 that still wouldn't result in your ask here - alright onto another pr I go!

**Comment by Thorinair** [comment]
Maybe we could introduce a toggle that enables or disables whether the produce accumulates thru the season for the dehydrator, so you can pick whether its per harvest or total?

**Comment by doodlebunnyhops** [comment]
I like that idea! Haha on it 😊

**Pull request merged**
