### PR TITLE
Attemps to had dehydrator calculator

### PR DESCRIPTION
**Pull request by Tenebrosful**
- Needs Math checkup (probably wrong because i don't take in count the time to growth 5 exemples)

### CODE REVIEW

**Comment by Thorinair** [comment]
I have done a lot of commits merging various PRs in and implementing many fixes and additions. I suggest pulling the master again before continuing so you don't end up with tons of conflicts! And do let me know when you figure the math and stuff, it would be cool to have it as an additional produce type :)

**Comment by Tenebrosful** [comment]
I'm not really good at this, that's why i opened an draft PR to allow people to try thinking about this part

**Comment by doodlebunnyhops** [comment]
@Tenebrosful I'd be happy to take a stab it this. Took a quick peek at what you've got so far, is your intent to include crop cost in dehydration process? My thoughts are this would add mushrooms as well - though I didn't see them added in crops.js

**Comment by Thorinair** [comment]
Mushrooms are indeed not in the crop list, as they aren't really growable in the traditional way. I am not sure if they should be added, or only the existing fruits should be calculated.

**Comment by doodlebunnyhops** [comment]
I'd be in favor for first pass just including fruits + crop eval, and can include a wiki link to the mushroom. Open to thoughts 🥰 and opinions.

**Pull request closed without merging**
